# Site settings
title: East Neuk Trinity
email:
description: > # this means to ignore newlines until "baseurl:"
  East Neuk Trinity, Church of Scotland<br />
  One Church - Three Centres of Worship
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: East Neuk Trinity Church
email: webmaster@eastneuktrinity.org.uk
facebook_username:
twitter_username: ekcchurch
github_username:
address:
  - line: Elie Parish Church, Main Street, Elie
  - line:
  # Feel free to add more lines here 
telephone: (01333) 340642
copyright: East Neuk Trinity

# API settings
google_api_key: AIzaSyBG1JbljIM9syp48e2PyMObv_j1aXe4ij0

# Build settings
markdown: kramdown

plugins: 
  - jekyll-paginate-v2

pagination:
  enabled: true

collections:
  activities:
     output: true
  plants:
    output: true

mini_magick:
  plant_thumbnail: # Preset name
    source: img/plant_images/originals # source directory - change this to whatever you want
    destination: img/plant_images/thumbnail # generated destination directory
    size: "600x600"
    resize: "300x300^"
    gravity: "center"
    extent: "300x300"
  plant_large: # Preset name
    source: img/plant_images/originals # source directory - change this to whatever you want
    destination: img/plant_images/large # generated destination directory
    resize: "1200x1200^"