# Site settings
title: East Neuk Trinity
email:
description: > # this means to ignore newlines until "baseurl:"
  East Neuk Trinity Church of Scotland<br />
  One Church - Three Centres of Worship
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: East Neuk Trinity Church
email: webmaster@eastneuktrinity.org.uk
facebook_username:
twitter_username: ekcchurch
github_username:
address:
  - line: Elie Parish Church, Main Street, Elie
  - line:
  # Feel free to add more lines here 
telephone: (01333) 340642
copyright: East Neuk Trinity

# API settings
google_api_key: AIzaSyDpmYlUBTrPIdfkGRm0dpBBIS-qqnE3prQ

# Build settings
markdown: kramdown
